# Print the inroduction
puts "Welcome to the Mastermind Game!
A game so intellectually challenging it will blow your mind.

The goal here is to guess the four secret colour code generated by the computer and its selected order. It's you against the computer! You will only have TEN attempts."

# Print the rules
puts "Guess the four colours. You can choose from the following:
Blue (b), Orange (o), Red (r), purple (p), Green (g), and Yellow (y)
You will enter your guess as such: obgy or ggrp

If you guessed a correct colour in a correct position, you will receive a gold pin.
If you guessed a correct colour but it's position is incorrect, you will receive a black pin.

Do you think you can handle it?"

# Have the user guess the colour code.
puts "Guess the generated four colours." 
the_guess = gets.chomp

# Code stuff
the_colours = ["b", "o", "r", "p", "g", "y"]





# Have their guess return on screen as true or false....